### ISSUE TITLE
index out of bounds: the len is 0 but the index is 0

### ISSUE THREAD

**Issue by yunweb** [pyth-network/pyth-client-rs#4]
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/user/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/pyth-client-0.2.2/src/lib.rs:141:4

**Comment by amin1419** [comment]
https://github.com/pyth-network/pyth-client-rs/issues/4#issue-974786902

**Comment by amin1419** [comment]
> thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/user/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/pyth-client-0.2.2/src/lib.rs:141:4
